# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Trace < Formula
  desc "CLI for the Trace install attribution and deep links platform"
  homepage "https://traceclick.io"
  version "0.6.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bmcreations/homebrew-tap/releases/download/v0.6.0/trace_darwin_amd64.tar.gz"
      sha256 "a4a129db646a58b8e16f4e846b9f65f615fa08186fb22d09842360ca586a77c1"

      define_method(:install) do
        bin.install "trace"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bmcreations/homebrew-tap/releases/download/v0.6.0/trace_darwin_arm64.tar.gz"
      sha256 "7b5cc3163521085baf2595c911a580e4b0ff43f244c9992a37ff63034d5b251b"

      define_method(:install) do
        bin.install "trace"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/bmcreations/homebrew-tap/releases/download/v0.6.0/trace_linux_amd64.tar.gz"
      sha256 "6e85de4ff93d65ada02d9f9cd113034a92abddc9223703b6c5a036b07feadb52"
      define_method(:install) do
        bin.install "trace"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bmcreations/homebrew-tap/releases/download/v0.6.0/trace_linux_arm64.tar.gz"
      sha256 "de3cc4888e36a90512a0cb0535a1d40299a0497bb07a2b49963ecb1d93c85c59"
      define_method(:install) do
        bin.install "trace"
      end
    end
  end

  test do
    system "#{bin}/trace", "version"
  end
end
